// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
	RECIPIENT_ADDRESS: string;
	SENDER_ADDRESS: string;
	ALLOWED_ORIGINS: string;
	EMAIL_RATE_LIMIT: any;
	SEB: SendEmail;
}
