#:schema node_modules/wrangler/config-schema.json
name = "email-workers"
main = "src/index.ts"
compatibility_date = "2024-09-25"

send_email = [
    {name = "SEB", allowed_destination_addresses = [ "<RECIPIENT>@example.com" ]},
]

[observability]
enabled = true

[vars]
ALLOWED_ORIGINS = "*"
RECIPIENT_ADDRESS = "<RECIPIENT>@example.com"
SENDER_ADDRESS = "<SENDER>@example.com"
